openapi: 3.0.0
info:
  title: Users API for "Лаборатория интернет"
  version: 1.0.0
servers:
  - url: api/v1

tags:
   - name:  users
     description: Users Resource

paths:
  /users:
    post:
      tags:
        - users
      description: Create User
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schema/users.yaml#/UserCreateOrUpdateRequest'
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    example: []